---
kind: pipeline
type: kubernetes
name: linter

platform:
  os: linux
  arch: amd64

steps:
- name: helm lint
  commands:
  - helm lint
  image: docker.io/volkerraschek/helm:3.8.2
  resources:
    limits:
      cpu: 50
      memory: 50M

- name: markdown lint
  commands:
  - markdownlint *.md
  image: docker.io/volkerraschek/markdownlint:0.31.1
  resources:
    limits:
      cpu: 50
      memory: 50M

- name: email-notification
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 50
      memory: 25M
  when:
    status:
    - changed
    - failure

trigger:
  event:
    exclude:
    - tag

---

kind: pipeline
type: kubernetes
name: release

platform:
  os: linux

steps:
- name: release-helm-chart
  commands:
  - helm repo add volker.raschek https://charts.cryptic.systems/volker.raschek
  - helm package --version ${DRONE_TAG} .
  - helm cm-push ${DRONE_REPO_NAME%-charts}-${DRONE_TAG}.tgz volker.raschek
  environment:
    HELM_REPO_PASSWORD:
      from_secret: helm_repo_password
    HELM_REPO_USERNAME:
      from_secret: helm_repo_username
  image: docker.io/volkerraschek/helm:3.8.2

trigger:
  event:
  - tag
  repo:
  - volker.raschek/roundcube-charts
