apiVersion: v2
name: roundcube
description: Helm chart for roundcube
type: application
version: "0.2.1"
appVersion: "1.5.2-apache"
icon: https://upload.wikimedia.org/wikipedia/commons/e/e3/Roundcube_logo_icon.svg

keywords:
- roundcube
- webmail

sources:
- https://github.com/volker-raschek/roundcube-charts
- https://github.com/roundcube/roundcubemail
- https://hub.docker.com/r/roundcube/roundcubemail/

maintainers:
- name: Markus Pesch
  email: markus.pesch+apps@cryptic.systems
